language: node_js
node_js:
- 10
before_script:
- npm install -g gulp-cli
script:
- npm run build
services: mongodb
cache:
  directories:
  - node_modules
env:
  matrix:
  - CXX=g++-4.8
  global:
  - secure: HHV/M467tWnJX1rbAdxNDSYrCOhs2v9fvSu68LVkE72JU+X0cFA/EXSB/Gt88mo53vYyOhJVSLNzw2M9hEHobLcBqBNUS/37sFEJkx1aFPtVbordPKNeBnCVATGZdLvh+D5pqSl9OGkDIT88eQdqNEWK/xLGgotXrGAUftbfgHhxmwskjDkCSdfGEl1X2b1ET8M+KgGIDJEouqnvyKUGdD8E+HwEZZc6Y2HVVIN3w7FlYTcgH0QiSLd4FusWFmFnQP858jfD8Qo8AZmRMvkKBx8ONMqP+aYwysvM5gFGB75pyUzKBoCG11w0Qr4+I8jiC2dYf6wcZQigABoRFuOqo2NXushxin1Fm6WO8zj925bJkZBwnaSpIHNQY3CureMi51tzpy0vs46RoAB9ooMyu8KElOFyag7DdwQk/59fEN2R73w7zs209Bsgho4evvBIPhDclVmmvHU2sK7R/2wAVC3bTkuNPNdU7tyeUQCOuxYbxezajWhYTuwOvIGamJtv1Iq7rijlWDFZbddENWshYu7ERXcwfIrRamgG9Px6X0guAJc6SkJRIOo5jAZoDRzLGN8KdBOIzVgcWi5HMFBbQEBUtZrwRb26jMVbDumxVCYgauJAEznZ0/aWqkLKN4+iER6w2es2kvN9qfIccykNtQzuBIzxbrDIJ+O6WS1OYyU=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
deploy:
  provider: heroku
  api_key:
    secure: mNZnDCrLMpRNZfGeXwChF8knd59B+RDhHys6TyhFgiJhJHmfqRUn3eb5tRutWxsaz9KxDETHVHEFSP4DSDeArIhBBs5hWhLGlS318spc912nSqrcmvmlouw3wxrl0GUItyhn2jVa6B9ivt/fN9WXwYb3x+ggZr07vCJkCt19gpZtLNGYIjauh3XMIK3dfSmaisFVtDCPBfWlPOVMqK8y90JSvXK3AvVM8aES5y0Yur4XcJK6qmF1HqEiCqamd5ipbrlg434b7I+B2GPTOarQ8DkaFaOPFCIJx9hbIrLDAvDcMdWPdDSF/Aw1pFZGol9pjqc8CBtrPIUHmEU6sYoH5Fj2EuhHTXF6TppkSWuJMl9rUCw2+fIsiHx/4ADMFJcpVlX+yxGzUPYtBIv1JioQFbTD6bPHBzsbmAIONWx/a7FfUPN2i70wpSOpi3MkmaHpE1Xt931LwWV54LBDfExWNrJSg1oQttkF1zr4CBrOvAtpDSvLxDK76KfTu+cYkBsREoHk5PPiLQEEbpx3mOlUgpZ3qWQdJ6FFwZNvRWP7QMPf3r1GHbDzL0tPpMeiITZ/x8FLu30tiv8oPCISUTZPQ23dmyVixXn1qO8CFOwFrx1T++X1DXGHAIxA8yiVZBaCFXIlC0cWrI2eU1YM/n78xaWfCyQQ04vbpkIWglowwB8=
